apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-app
  labels:
    app: quiz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-app
  template:
    metadata:
      labels:
        app: quiz-app
    spec:
      containers:
      - name: quiz-app-container
        image: manupanand/quiz-app:1.0 # Replace with your Docker Hub username and image tag
        ports:
        - containerPort: 2500
