# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: QUIZ APP Node.js CI deploy EC2

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [ 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: | 
        npm ci
        pm2 stop all
        pm2 delete all
        pm2 kill
        npm install
        pm2 start /home/ubuntu/actions-runner/_work/project-quiz-app/project-quiz-app/src/index.js --name "quizapp" || pm2 restart "quizapp"
        pm2 save

      # Start or restart the app with PM2

        #pm2 start /actions-runner/_work/project-quiz-app/project-quiz-app/server/main.js --name "quizapp" || pm2 restart "quizapp"

    # Save the PM2 process list (optional)
        #pm2 save
    # - run: npm run build --if-present
    # - run: npm test
    # - run: |
    #    touch .env
    #    echo "${{secrets.PROD_ENV_FILE}}" > .env
